version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04-daemonset

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yml
      - kubens ${NAMESPACE}

  02-apply-minimal-pod:
    desc: "Apply a minimal fluentd pod configuration"
    cmds:
      - kubectl apply -f Pod.fluentd-minimal.yml

  03-apply-minimal-daemonset:
    desc: "Apply a minimal fluentd daemonset configuration"
    cmds:
      - kubectl apply -f DaemonSet.fluentd-minimal.yml

  04-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - kubectl delete -f Namespace.yml