apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-postgresql
  namespace: postgres 
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-postgresql
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_PASSWORD
            value: "mysecretpassword"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: www
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
