version: "3"

env:
  BORDER: double
  BORDER_BACKGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04-service

tasks:
   01-create-namespace:
     desc: "Create a namespace for the Service demo and switch to it"
     cmds:
       - kubectl create -f Namespace.yml
       - kubens ${NAMESPACE}
  
   02-apply-deployment:
      desc: "Apply the Deployment for the Service demo"
      cmds: 
        - kubectl create -f Deployment.yml

   03-apply-clusterip:
      desc: "Apply the ClusterIP Service"
      cmds: 
        - kubectl create -f ClusterIP.yml

   04-apply-nodeport-service:
    desc: "Apply the  NodePort Service"
    cmds:
      - kubectl apply -f Service.nginx-nodeport.yml

   05-apply-loadbalancer-service:
     desc: "Apply the  LoadBalancer Service"
     cmds:
      - kubectl apply -f Service.nginx-loadbalancer.yml

   06-delete-namespace:
     desc: "Delete the namespace to clean up"
     cmds:
      - kubectl delete -f Namespace.yml
      
