apiVersion: apps/v1
kind: ReplicaSet 
metadata:
   name: replicaset-nginx-minimal
spec:
    replicas: 2
    selector:
      matchLabels:
        key: replicaset-nginx-minimal
    template:
      metadata:
        labels:
          key: replicaset-nginx-minimal
      spec:
        containers:
          - name: nginx
            image: nginx:1.26.0
  