apiVersion: v1
kind: Service 
metadata:
  - name: nginxs
spec:
  type: ClusterIP
  clusterIP: none
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetport: 80