apiVersion: v1
kind: Service 
metadata:
  name: nginxs
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80