apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-better
  namespace: my-pod
  labels:
    app: deployment-nginx-better
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-nginx-better
  template:
    metadata:
      labels:
        app: deployment-nginx-better
    spec:
      containers:
      - name: nginx
        image: cgr.dev/chainguard/nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet: 
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10  
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        
