version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: my-pod

tasks:
   01-create-namespace:
      desc: "Create a namespace for the deployment"
      cmds:
          - kubectl create -f Namespace.yml
          - kubens ${NAMESPACE}

   02-apply-minimal:
      desc: "Apply the minimal deployment configuration"
      cmds:
          - kubectl apply -f Deployment.nginx.minimal.yml    

   03-apply-better:
      desc: "Apply the better deployment configuration"
      cmds:
          - kubectl apply -f Deployment.nginx.better.yml

   04-rollout-restart:
      desc: "Restart the deployment to apply changes"
      cmds:
          - kubectl rollout restart deployment deployment-nginx-better 
          - watch "kubectl get pods"

   05-cleanup-namespace:
      desc: "Clean up the namespace and all resources"
      cmds:
          - kubectl delete namespace ${NAMESPACE}