apiVersion: v1
kind: Secret
metadata:
  name: api-node
  namespace: demo-app
type: Opaque
data:
 DATABASE_URL: postgres://postgres:foobarbaz@postgres-postgresql.postgres.svc.cluster.local:5432/postgres
